### ISSUE TITLE
Participant doesn't load if there is no folder open

### ISSUE THREAD

**Issue by burkeholland** [microsoft/copilot-pg#15]
If you try and use the participant with no folder open, you get `No activate agend with id "dba.pg`. Maybe this is how the API's work? That custom participants aren't loaded until a folder is? Participants like `@workspace` still function with no folder open even though the response is, "I'm sorry, I can't answer that question with what I currently know about your workspace".

![Image](https://github.com/microsoft/copilot-pg/assets/686963/3eba13f7-1fca-4310-b4a3-1e9e23c4627e)

**Comment by robconery** [comment]
Hmmm - yeah I don't know how to get around that one. I'll have a look.

**Comment by robconery** [comment]
I think this is a limitation of chat...
