### ISSUE TITLE
/conn closes and throws an error when focus is lost

### ISSUE THREAD

**Issue by burkeholland** [microsoft/copilot-pg#17]
When setting the connection string, I find myself tabbing back to postgres to get the connection info and when focus is lost, it looks like `/conn` goes ahead and returns whatever value is in the pop-up as the submitted value. If that value is empty, the following error gets thrown....

![Image](https://github.com/microsoft/copilot-pg/assets/686963/571d6998-5494-42ac-95ff-9d327e8a2cbb)

**Comment by robconery** [comment]
I don't think it makes sense to have an input box here - it removes the idea of "chatting". I'm just going to remove...
