### ISSUE TITLE
Report when connection string is under-privileged

### ISSUE THREAD

**Issue by burkeholland** [microsoft/copilot-pg#18]
I am connecting with a `demoUser` that has full access to the demos database, but when calling `/show`, the participant reports that the connection string is bad. I assume it's not bad, but rather that `demoUser` does not have permissions to pull the database schema. However, my pg knowledge is fairly paltry so that may not be what's happening here.

**Comment by robconery** [comment]
I *think* the only way to do this is with a better error message, which I added. I don't have an answer yet for the .ENV thing but I'm still working on it. Pretty sure it's a windows pathing thing.
