### ISSUE TITLE
Install Instructions?

### ISSUE THREAD

**Issue by jhancock-taxa** [microsoft/copilot-pg#21]
How do we install this?

**Comment by jeaneric** [comment]
I followed those instructions and I got it installed. 
https://stackoverflow.com/a/54409592/140384

**Comment by robconery** [comment]
In VS Code you go to Extensions and search for "PG Chat" and you should see it there.

**Comment by robconery** [comment]
Also - make sure you're using VS Code Insiders. Closing for now - leave a comment if you still can't get it installed through the extensions tab.
